# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:49

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='DbFileInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DbPath', models.CharField(max_length=200)),
                ('TablePath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DbInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DbName', models.CharField(max_length=50)),
                ('TableName', models.CharField(max_length=500)),
                ('UpTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DbUserInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostUser', models.CharField(max_length=20)),
                ('HostPwd', models.CharField(max_length=100)),
                ('AddTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostIp', models.GenericIPAddressField(unique=True)),
                ('HostName', models.CharField(default=None, max_length=100, null=True)),
                ('HostDescription', models.CharField(max_length=500)),
                ('DelBit', models.BooleanField(default=False)),
                ('AddTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostProject',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web1.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostUserInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('HostUser', models.CharField(max_length=100)),
                ('HostPwd', models.CharField(max_length=100)),
                ('AddTime', models.DateTimeField(auto_now_add=True)),
                ('HostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='IpGrouping',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IpParagraph', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IpEndId', models.CharField(choices=[(1, '0-50'), (2, '51-100'), (3, '101-150'), (4, '151-200'), (5, '201-254')], max_length=1)),
                ('HostId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web1.HostInfo')),
                ('IpGroupingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.IpGrouping')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgectName', models.CharField(max_length=255, unique=True)),
                ('ProjectUser', models.CharField(max_length=500)),
                ('ProgectDescription', models.CharField(max_length=500)),
                ('DelBit', models.BooleanField(default=False)),
                ('AddTime', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaltInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UpTime', models.DateTimeField(auto_now=True)),
                ('SaltId', models.CharField(max_length=100)),
                ('HostId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web1.HostInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TEST1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=49)),
                ('password', models.CharField(max_length=49)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=49)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.UserType'),
        ),
        migrations.AddField(
            model_name='hostproject',
            name='ProjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.ProjectInfo'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='web1.User'),
        ),
        migrations.AddField(
            model_name='dbuserinfo',
            name='HostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.HostInfo'),
        ),
        migrations.AddField(
            model_name='dbinfo',
            name='HostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.DbUserInfo'),
        ),
        migrations.AddField(
            model_name='dbfileinfo',
            name='HostId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web1.HostInfo'),
        ),
        migrations.AddField(
            model_name='assert',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.Group'),
        ),
    ]
