# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assert',
            name='user_group',
        ),
        migrations.DeleteModel(
            name='Assert',
        ),
    ]
