# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-27 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20170324_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostuserinfo',
            name='LoginBit',
            field=models.BooleanField(default=False),
        ),
    ]
