# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-27 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_auto_20170322_1454'),
        ('web1', '0004_hostuserinfo_loginbit'),
    ]

    operations = [
    ]
