# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-27 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0005_merge_20170327_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='ProjectManager',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
