# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0006_projectinfo_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='UpdateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
